 'use strict';
let notificationChannels={revision:0,channels:{}};
function runNotificationRoute(r){return r.settings.notification_route||(r.settings.notification_command?.length?'user':'workspace');}
function outletOptions(selected='default',withDefault=true,portable=false){const values={...(withDefault?{default:'本次运行默认出口'}:{}),workspace:'平台通知区',...(!portable?{user:'沿用本次发送命令'}:{}),...Object.fromEntries(Object.entries(portable?{}:notificationChannels.channels).map(([id,c])=>[id,c.label||id]))};if(selected&&!Object.hasOwn(values,selected))values[selected]=selected+'（尚未配置）';return Object.entries(values).map(([id,label])=>`<option value="${esc(id)}" ${id===selected?'selected':''}>${esc(label)}</option>`).join('');}
function renderOutletSelect(id,value){const el=$(id);if(el){el.innerHTML=outletOptions(value,false);el.value=value;}}
async function loadNotificationChannels(){notificationChannels=await api('notification-channels');document.querySelectorAll('[data-outlet-select]').forEach(el=>el.innerHTML=outletOptions(el.value||'workspace',el.dataset.outletSelect!=='run'));return notificationChannels;}
function noticeFields(notice={message:''},portable=false){return `<div class="notice-fields"><label>通知内容<textarea data-notice-message rows="3">${esc(notice.message)}</textarea></label><label>通知出口<select data-notice-route>${outletOptions(notice.route||'default',true,portable)}</select></label><label class="inline-check"><input data-notice-question type="checkbox" ${notice.reply?'checked':''}>需要用户回复</label><div data-notice-reply ${notice.reply?'':'hidden'}><p class="small muted">通知本身不暂停。需要答案时，安排同事件名称和关联标识的等待节点。</p><label>回复事件<input data-reply-event value="${esc(notice.reply?.event||'reply')}"></label><label>关联标识<input data-reply-key value="${esc(notice.reply?.key||'')}" placeholder="例如 budget-1 或 {parameters.request_id}"></label><details><summary>回复的数据结构</summary><textarea data-reply-schema rows="6">${esc(pretty(notice.reply?.schema||{type:'object',properties:{answer:{type:'string'}},required:['answer']}))}</textarea></details></div></div>`;}
function readNotice(root){const result={message:root.querySelector('[data-notice-message]').value,route:root.querySelector('[data-notice-route]').value};if(root.querySelector('[data-notice-question]').checked)result.reply={event:root.querySelector('[data-reply-event]').value,key:root.querySelector('[data-reply-key]').value,schema:JSON.parse(root.querySelector('[data-reply-schema]').value)};return result;}
document.addEventListener('change',e=>{if(e.target.matches('[data-notice-question]'))e.target.closest('.notice-fields').querySelector('[data-notice-reply]').hidden=!e.target.checked;});
$('loop_definitions-nav').insertAdjacentHTML('afterend','<button class="nav" id="notification-outlets">◇ <span>通知出口</span></button>');
const outletDialog=document.createElement('dialog');outletDialog.id='outlet-dialog';outletDialog.innerHTML='<div class="dialog-heading"><h2>平台通知出口</h2><button class="close-dialog">×</button></div><p class="small muted">平台通知区始终可用。外部出口只保存在当前平台，不随 Loop 分享；发送身份和连接由你的桥接配置提供。</p><div id="outlet-list"></div><button id="add-outlet">＋ 添加出口</button><button class="primary" id="save-outlets">保存出口设置</button>';document.body.append(outletDialog);
function outletRow(id='',c={}){return `<section class="outlet-row"><div class="candidate-identity"><label>出口标识<input data-outlet-id value="${esc(id)}" placeholder="work-chat"></label><label>显示名称<input data-outlet-label value="${esc(c.label||'')}"></label></div><div class="candidate-identity"><label>渠道<select data-outlet-channel>${['飞书','微信','其他'].map(v=>`<option ${(c.channel||'其他')===v?'selected':''}>${v}</option>`).join('')}</select></label><label>发送方式<select data-outlet-adapter><option value="command">通用通知命令</option><option value="cc-connect" ${c.command?.some(v=>v.endsWith('/notify_cc_connect.py'))?'selected':''}>cc-connect</option></select></label></div><label>发送身份 / 项目<input data-outlet-identity value="${esc(c.identity||'')}" placeholder="cc-connect project，或适配器识别的身份"></label><label>接收位置 / 会话<input data-outlet-destination value="${esc(c.destination||'')}" placeholder="cc-connect session，或适配器识别的目的地"></label><label>发送命令（每行一个参数）<textarea data-outlet-command rows="4">${esc((c.command||[]).join('\n'))}</textarea></label><p class="small muted">通用适配器从通知 JSON 的 outlet.identity / destination 读取身份和目的地。cc-connect 由平台提供适配脚本，桥接需已连接目标渠道。</p><div class="candidate-identity"><label>工作目录（可选）<input data-outlet-cwd value="${esc(c.cwd||'')}"></label><label>发送超时秒数<input data-outlet-timeout type="number" min="1" value="${esc(c.timeout||30)}"></label></div><button data-remove-outlet>移除此出口</button></section>`;}
document.addEventListener('change',e=>{if(e.target.matches('[data-outlet-adapter]')&&e.target.value==='cc-connect')e.target.closest('.outlet-row').querySelector('[data-outlet-command]').value=(notificationChannels.cc_connect_command||[]).join('\n');});
document.addEventListener('click',e=>safely(async()=>{const el=e.target.closest('button');if(!el)return;
 if(el.id==='notification-outlets'){await loadNotificationChannels();$('outlet-list').innerHTML=Object.entries(notificationChannels.channels).map(([id,c])=>outletRow(id,c)).join('');outletDialog.showModal();}
 if(el.id==='add-outlet')$('outlet-list').insertAdjacentHTML('beforeend',outletRow());
 if(el.hasAttribute('data-remove-outlet'))el.closest('.outlet-row').remove();
 if(el.id==='save-outlets'){const channels=Object.create(null);for(const row of $('outlet-list').children){const get=k=>row.querySelector('[data-outlet-'+k+']').value,id=get('id').trim();if(!id||Object.hasOwn(channels,id))throw new Error('出口标识不能为空或重复');const c={label:get('label'),channel:get('channel'),identity:get('identity'),destination:get('destination'),command:get('command').split('\n').filter(Boolean),timeout:Number(get('timeout'))};if(get('cwd'))c.cwd=get('cwd');channels[id]=c;}await platformCall('set_notification_channels',{revision:notificationChannels.revision,channels});await loadNotificationChannels();outletDialog.close();toast('通知出口已保存');}
}));
const noticeDialog=document.createElement('dialog');noticeDialog.id='notice-dialog';document.body.append(noticeDialog);
function notificationCards(){return run.notifications.map(n=>`<article class="notification-card"><div class="task-detail-heading"><strong>${esc(n.message)}</strong>${badge(n.status)}</div><p class="small muted">${esc(n.sender?.label||(n.route==='workspace'?'平台通知区':n.route))} · ${esc(taskTime(n.at))}${n.tasks?' · '+esc(run.loop_definition.nodes[run.tasks[n.tasks]?.spec.node]?.label||n.tasks):''}</p>${n.reply?`<p class="small">需要回复 · ${run.events.some(e=>e.name===n.reply.event&&e.key===n.reply.key)?'已收到回复':'等待回复'}</p><button data-answer-notification="${esc(n.id)}" ${['completed','terminated'].includes(run.status)?'disabled':''}>回复此询问</button>`:''}${n.error?`<p class="task-error">${esc(n.error)}</p>`:''}${n.status==='fault'?`<button data-retry-notification="${esc(n.id)}">重试发送</button>`:''}<details><summary>送达记录</summary><pre>${esc(pretty({id:n.id,attempt:n.attempt,receipt:n.receipt,outlet:n.sender?Object.fromEntries(['channel','identity','destination'].filter(k=>k in n.sender).map(k=>[k,n.sender[k]])):null}))}</pre></details></article>`).join('')||'<p class="muted">还没有通知。</p>';}
function waitDetails(attempt){if(!attempt?.wait)return '';const w=attempt.wait;return `<div class="wait-description"><strong>${attempt.implementation.kind==='timer'?'等待时间':'等待事件：'+esc(attempt.implementation.event)}</strong>${w.until?`<p>唤醒时间：${esc(new Date(w.until*1000).toLocaleString())}</p>`:''}${w.key?`<p>关联标识：${esc(w.key)}</p>`:''}${w.deadline?`<p>截止时间：${esc(new Date(w.deadline*1000).toLocaleString())}</p>`:''}<p class="small muted">由 Engine 持久等待，不启动 Agent 或守候脚本。超时按本实现的状态转移处理。</p>${attempt.implementation.kind==='event'&&attempt.status==='waiting'?`<button data-complete-wait="${esc(attempt.task_id)}">提交事件 / 回复</button>`:''}</div>`;}
document.addEventListener('click',e=>safely(async()=>{const el=e.target.closest('button');if(!el||!run)return;
 if(el.id==='send-run-notice'){await loadNotificationChannels();noticeDialog.innerHTML=`<form id="send-notice-form"><div class="dialog-heading"><h2>发送通知或询问</h2><button type="button" class="close-dialog">×</button></div>${noticeFields()}<button class="primary">加入发送队列</button></form>`;noticeDialog.dataset.run=run.id;noticeDialog.dataset.key=randomKey();noticeDialog.showModal();}
 if(el.dataset.answerNotification||el.dataset.completeWait){const n=run.notifications.find(n=>n.id===el.dataset.answerNotification),task=run.tasks[el.dataset.completeWait],attempt=task&&run.executions.find(x=>x.id===task.execution_id),spec=n?.reply,output=task&&run.loop_definition.nodes[task.spec.node].outputs,schema=spec?.schema||{type:'object',properties:Object.fromEntries(Object.entries(output||{}).map(([k,v])=>[k,run.loop_definition.records[v.record_type]])),required:Object.keys(output||{})};noticeDialog.innerHTML=`<form id="reply-notice-form"><div class="dialog-heading"><h2>${n?'回复询问':'提交等待的事件'}</h2><button type="button" class="close-dialog">×</button></div><p>${esc(n?.message||taskLabel(task))}</p><div id="event-reply-value">${valueField({},schema,'回复内容')}</div><button class="primary">提交回复</button></form>`;noticeDialog.reply={run_id:run.id,event_id:randomKey(),name:spec?.event||attempt.implementation.event,key:spec?.key||attempt.wait.key,...(n?{notification_id:n.id}:{task_id:task.id})};if(noticeDialog.reply.key==null)delete noticeDialog.reply.key;noticeDialog.showModal();}
}));
document.addEventListener('submit',e=>{if(!['send-notice-form','reply-notice-form'].includes(e.target.id))return;e.preventDefault();safely(async()=>{if(e.target.id==='send-notice-form')await platformCall('notify',{run_id:noticeDialog.dataset.run,key:noticeDialog.dataset.key,...readNotice(noticeDialog)});else await platformCall('send_event',{...noticeDialog.reply,payload:readValue($('event-reply-value').firstElementChild)});noticeDialog.close();inspectSignature='';await refresh();});});
loadNotificationChannels().catch(()=>{});

function outletLabel(id){return id==='workspace'?'平台通知区':id==='user'?'本次发送命令':id==='default'?'本次 Run 的通知出口':notificationChannels.channels[id]?.label||id||'平台通知区';}
function renderRunOutlet(){let el=$('run-outlet-summary');if(!el){el=document.createElement('div');el.id='run-outlet-summary';$('run-id').after(el);}el.innerHTML=`<span>通知出口：<strong>${esc(outletLabel(runNotificationRoute(run)))}</strong></span><button type="button" data-open-run-notices>通知安排与记录</button>${['completed','terminated'].includes(run.status)?'':'<button type="button" data-focus-outlet="run">修改出口</button>'}`;}
document.addEventListener('click',e=>{if(e.target.closest('[data-open-run-notices]')){activeTab='hooks';renderInspect();$('inspect').scrollIntoView({behavior:'smooth',block:'start'});}const b=e.target.closest('[data-focus-outlet]');if(!b)return;const input=$(b.dataset.focusOutlet==='run'?'run-notification-route':'launch-notification-route');if(!input)return;for(let p=input.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;input.scrollIntoView({behavior:'smooth',block:'center'});input.focus({preventScroll:true});});
